### ISSUE TITLE
Unable to deploy kubernetes anywhere using vsphere behind a firewall

### ISSUE THREAD

**Issue by jiopaley** [weaveworks/weave-kubernetes-anywhere#533]
When deploying kubernetes anywhere using the vsphere provider behind a firewall (ie no access to the internet, but with local docker repositories), the deployment attempts to retrieve containers from storage.googleapis.com:

null_resource.kubernetes-master (remote-exec): DEBUG    : files: createFilesystemsFiles: createFiles: GET error: Get https://storage.googleapis.com/kubernetes-release/release/v1.6.5/bin/linux/amd64/kubectl: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout

It looks like there isn't a parameter to control the location of these containers.  Request to add this as a parameter to the make config script!

**Comment by DHill-LMK** [comment]
I made a whole bunch of changes to get this to work in my environment: https://github.com/DHill-LMK/kubernetes-anywhere , you may find it useful if you need to do this style of deployment before there is official support.

There is also a rebuilt ignition container that gets referenced as I had trouble getting the HTTP proxy to work from within there.
